<#
.SYNOPSIS
    Starts the local 7 Days to Die dev server.

.DESCRIPTION
    Optionally builds/deploys the mod first, then launches the dedicated server
    using the dev configuration generated by setup-server.ps1.

.PARAMETER Build
    Run build.ps1 to validate and deploy the mod before starting.

.PARAMETER UseVanilla
    Launch with the server's default serverconfig.xml instead of serverconfig_dev.xml.

.EXAMPLE
    .\scripts\start-server.ps1
    .\scripts\start-server.ps1 -Build
#>
param(
    [switch]$Build,
    [switch]$UseVanilla
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# === Load Config =============================================================

$ProjectRoot = Split-Path $PSScriptRoot -Parent
$ConfigPath  = Join-Path $ProjectRoot "mod.config.json"

if (-not (Test-Path $ConfigPath)) {
    Write-Error "mod.config.json not found."
    exit 1
}

$Config    = Get-Content $ConfigPath | ConvertFrom-Json
$ServerDir = Join-Path $ProjectRoot "server"
$DataDir   = Join-Path $ProjectRoot "data"

# === Check Server ============================================================

$markerFile = Join-Path $ServerDir ".7d2d-dev-server"
$serverExe  = Join-Path $ServerDir "7DaysToDieServer.exe"

if (-not (Test-Path $markerFile)) {
    Write-Host ""
    Write-Host "Dev server not found. Run setup first:" -ForegroundColor Yellow
    Write-Host "  .\scripts\setup-server.ps1" -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

if (-not (Test-Path $serverExe)) {
    Write-Host "7DaysToDieServer.exe not found in: $ServerDir" -ForegroundColor Red
    exit 1
}

# === Optional Build ==========================================================

if ($Build) {
    Write-Host "Building mod..." -ForegroundColor Cyan
    & (Join-Path $PSScriptRoot "build.ps1")
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Build failed - server not started." -ForegroundColor Red
        exit 1
    }
}

# === Prepare Data Dirs =======================================================

foreach ($sub in @("logs", "Saves", "UserData")) {
    New-Item -ItemType Directory -Path (Join-Path $DataDir $sub) -Force | Out-Null
}

# === Determine Config File ===================================================

if ($UseVanilla) {
    $configFile = "serverconfig.xml"
} else {
    $configFile = "serverconfig_dev.xml"
    if (-not (Test-Path (Join-Path $ServerDir $configFile))) {
        Write-Host "serverconfig_dev.xml not found - falling back to serverconfig.xml." -ForegroundColor Yellow
        $configFile = "serverconfig.xml"
    }
}

# === Show Status =============================================================

$modsDir    = Join-Path $ServerDir "Mods"
$loadedMods = @()
if (Test-Path $modsDir) {
    $loadedMods = @(Get-ChildItem -Path $modsDir -Directory | Select-Object -ExpandProperty Name)
}

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$logFile   = Join-Path $DataDir "logs\server_$timestamp.log"
$logArg    = "..\data\logs\server_$timestamp.log"

Write-Host ""
Write-Host "=== Starting 7D2D Dev Server ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Config: $configFile"
Write-Host "  Log:    $logFile"
Write-Host "  Mods:   $(if ($loadedMods.Count -gt 0) { $loadedMods -join ', ' } else { '(none)' })"

$webEnabled = $Config.server.PSObject.Properties['webDashboardEnabled'] -and $Config.server.webDashboardEnabled
if ($webEnabled) {
    Write-Host "  Dashboard: http://localhost:$($Config.server.webDashboardPort)"
}

Write-Host ""
Write-Host "Press Ctrl+C to stop." -ForegroundColor DarkGray

# === Launch Server ===========================================================

$proc = Start-Process -FilePath $serverExe `
    -ArgumentList "-configfile=`"$configFile`"", "-logfile", "`"$logArg`"", "-quit", "-batchmode", "-nographics" `
    -WorkingDirectory $ServerDir `
    -PassThru

Write-Host "Server PID: $($proc.Id)" -ForegroundColor DarkGray
Write-Host ""

# Tail the log as it appears
$logReady = $false
$waited   = 0
while (-not $logReady -and $waited -lt 60) {
    Start-Sleep -Milliseconds 500
    $waited++
    if (Test-Path $logFile) { $logReady = $true }
}

if ($logReady) {
    Write-Host "--- Server Log ---" -ForegroundColor DarkGray
    Get-Content $logFile -Wait -Tail 0 | ForEach-Object {
        if ($_ -match "\[ERR\]|Exception") {
            Write-Host $_ -ForegroundColor Red
        } elseif ($_ -match "\[WRN\]|Warning") {
            Write-Host $_ -ForegroundColor Yellow
        } else {
            Write-Host $_
        }
    }
} else {
    Write-Host "Log file not created within 30s. Server may have failed to start." -ForegroundColor Yellow
    $proc.WaitForExit()
}
